kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    # Cooks
    path("cooks/", CookListView.as_view(), name="cooks-list"),
    path("cooks/<int:pk>/detail/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    # Dishes
    path("dishes/", DishListView.as_view(), name="dishes-list"),
    path("dishes/<int:pk>/detail/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    # Dish types
    path("dish-types/", DishTypeListView.as_view(), name="dish-types"),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
]

app_name = "kitchen"

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
        <ul class="pagination">

          {% if page_obj.has_previous %}
            <li class="mr-2 btn btn-outline-secondary">
              <a href="?{% query_transform request page=page_obj.previous_page_number %}"><--</a>
            </li>
          {% endif %}

          <li class="btn btn-outline-secondary">
            {{ page_obj.number }} of {{ paginator.num_pages }}
          </li>

          {% if page_obj.has_next %}
            <li class="ml-2 btn btn-outline-secondary">
              <a href="?{% query_transform request page=page_obj.next_page_number %}">--></a>
            </li>
          {% endif %}

        </ul>

      {% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
   {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item">
    <a href={% url "kitchen:index" %}>Homepage</a>
  </li>
  <li class="list-group-item">
    <a href={% url "kitchen:cooks-list" %}>Our cooks</a>
  </li>
  <li class="list-group-item">
    <a href={% url "kitchen:dish-types" %}>Dish types</a>
  </li>
  <li class="list-group-item">
    <a href={% url "kitchen:dishes-list" %}>Our dishes</a>
  </li>
</ul>