kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    # Cooks
    path("cooks/", CookListView.as_view(), name="cooks-list"),
    path("cooks/<int:pk>/detail/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    # Dishes
    path("dishes/", DishListView.as_view(), name="dishes-list"),
    path("dishes/<int:pk>/detail/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    # Dish types
    path("dish-types/", DishTypeListView.as_view(), name="dish-types"),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
]

app_name = "kitchen"

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
]

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["username"]
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name}"


class DishType(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.CharField(max_length=255)
    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
    )
    dish_type = models.ForeignKey(
        to=DishType,
        on_delete=models.CASCADE,
        related_name="dish",
    )
    cooks = models.ManyToManyField(
        to=Cook,
        related_name="dish",
    )

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name}"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from kitchen.models import Cook, Dish


def validate_experience(years):
    if years > 40:
        raise ValidationError("Experience can not be more than 40 years")
    if years < 1:
        raise ValidationError("We need experience chef on the kitchen")

    return years


class CookForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = (
            "username",
            "first_name",
            "last_name",
            "years_of_experience",
        )

    def clean_years_of_experience(self):
        return validate_experience(self.cleaned_data["years_of_experience"])


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter a dish name"}),
    )


class DishTypeSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter a dish type name"}),
    )


class CookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Enter a cook's name"}),
    )

kitchen/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    DishSearchForm,
    CookSearchForm,
    DishTypeSearchForm,
    CookForm,
    DishForm,
)
from kitchen.models import Cook, Dish, DishType


def index(request):
    cooks = Cook.objects.count()
    dishes = Dish.objects.count()

    context = {
        "num_cooks": cooks,
        "num_dishes": dishes,
    }

    return render(request, "kitchen/index.html", context=context)


class DishListView(generic.ListView):
    model = Dish
    queryset = Dish.objects.all().select_related("dish_type")
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = DishSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(name__icontains=form.cleaned_data["title"])

        return self.queryset


class DishDetailView(generic.DetailView):
    model = Dish
    fields = "__all__"
    queryset = Dish.objects.all().prefetch_related("cooks")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dishes-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dishes-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dishes-list")


class DishTypeListView(generic.ListView):
    model = DishType
    paginate_by = 5
    queryset = DishType.objects.all()
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = DishTypeSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        title = self.request.GET.get("title")

        if title:
            return self.queryset.filter(name__icontains=title)

        return self.queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-types")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-types")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-types")


class CookListView(generic.ListView):
    model = Cook
    queryset = Cook.objects.all()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = CookSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                first_name__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class CookDetailView(generic.DetailView):
    model = Cook
    fields = "__all__"
    queryset = Cook.objects.all().prefetch_related("dish")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("kitchen:cooks-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("kitchen:cooks-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cooks-list")

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Do you want to delete the cook?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block title %}
  <title>{{ cook.first_name }} {{ cook.last_name }}</title>
{% endblock %}

{% block content %}
  <h2>{{ cook.first_name }} {{ cook.last_name }}</h2>
  <h4>Experience: {{ cook.years_of_experience }} years</h4>
  <br>

  {% if user.is_authenticated %}
    <div class="mb-4">
      <a class="btn btn-outline-secondary mr-4" href={% url "kitchen:cook-update" pk=cook.id %}>Update</a>
      <a class="btn btn-outline-danger" href={% url "kitchen:cook-delete" pk=cook.id %}>Delete</a>
    </div>
  {% endif %}

  <hr>

  <p>Is responsible for:</p>

  <ul>
    {% for dish in cook.dish.all %}
      <li>
        <strong>
          <a href={% url "kitchen:dish-detail" pk=dish.id %}>{{ dish.name }}</a>
        </strong> ({{ dish.price }} USD)
      </li>
    {% endfor %}

  </ul>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} a cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Our cooks</title>
{% endblock %}

{% block content %}
  <h2>Our cooks</h2>
  <br>

  {% if user.is_authenticated %}
    <a class="btn btn-outline-primary mb-4" href={% url "kitchen:cook-create" %}>Create a cook</a>
  {% endif %}

  <form class="form-inline mb-4" action="">
    {{ search_form|crispy }}
    <input class="btn btn-outline-primary" type="submit" value="Search">
  </form>

  {% if cook_list %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Last name</th>
        <th>Experience</th>
      </tr>
      </thead>
      <tbody>
      {% for cook in cook_list %}
        <tr>
          <td>
            <a href={% url "kitchen:cook-detail" pk=cook.id %}>{{ cook.first_name }}</a>
          </td>
          <td>
            <a href={% url "kitchen:cook-detail" pk=cook.id %}>{{ cook.last_name }}</a>
          </td>
          <td>{{ cook.years_of_experience }} years</td>
        </tr>

      {% endfor %}

      </tbody>
    </table>

  {% else %}
    <p>Sorry, no cooks found. Strange...</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Do you want to delete the dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block title %}
  <title>{{ dish.name }}: {{ dish.price }} USD</title>
{% endblock %}

{% block content %}
  <h4>{{ dish.name }}</h4>
  <p>Price: {{ dish.price }} USD</p>

  {% if user.is_authenticated %}
    <a class="btn btn-outline-secondary mr-4" href={% url "kitchen:dish-update" pk=dish.id %}>Update</a>
    <a class="btn btn-outline-danger" href={% url "kitchen:dish-delete" pk=dish.id %}>Delete</a>
    <br>
  {% endif %}

  <br>

  <p>{{ dish.description }}</p>

  <br>
  <hr>

  <h5>Who can cook it for you?</h5>
  <br>

  {% if dish.cooks %}
    {% for cook in dish.cooks.all %}
      <p>
        <a href={% url "kitchen:cook-detail" pk=cook.id %}>{{ cook.first_name }} {{ cook.last_name }}</a>
      </p>


    {% endfor %}


  {% endif %}
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Our dishes</title>
{% endblock %}

{% block content %}
  <h2>Everything you can eat!</h2>
  <br>

  {% if user.is_authenticated %}
    <a class="btn btn-outline-primary mb-4" href={% url "kitchen:dish-create" %}>Create a new dish</a>
    <br>
  {% endif %}

  <form class="form-inline mb-4" action="">
    {{ search_form|crispy }}
    <input class="btn btn-outline-primary" type="submit" value="Search">
  </form>

  {% if dish_list %}
    <table class="table table-striped"">
    <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Cost</th>
    </tr>
    </thead>
    <tbody>

    {% for dish in dish_list %}
      <tr>
        <td>{{ dish.dish_type }}</td>
        <td>
          <a href={% url "kitchen:dish-detail" pk=dish.id %}>{{ dish.name }}</a>
        </td>
        <td><strong>{{ dish.price }}</strong> USD</td>
      </tr>
    {% endfor %}

    </tbody>
    </table>
  {% else %}
    <p>Sorry. No dishes yet...</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Do you want to delete the dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>All the dish types</title>
{% endblock %}

{% block content %}
  <h2>All the dish types we serve here</h2>
  <br>

  {% if user.is_authenticated %}
    <a class="btn btn-outline-primary mb-4" href={% url "kitchen:dish-type-create" %}>
      Create a new type
    </a>
    <br>
  {% endif %}

  <form class="form-inline mb-4" action="">
    {{ search_form|crispy }}
    <input class="btn btn-outline-primary" type="submit" value="Search">
  </form>

  {% if dish_type_list %}
    {% for dish_type in dish_type_list %}

      <table class="table table-striped dish-type-table">
        <thead>
          <tr>
            <th colspan="2">{{ dish_type.name }}</th>
          </tr>
        </thead>

        <tbody>

          {% if dish_type.dish.all %}
          {% for dish in dish_type.dish.all %}
            <tr>
              <td>
                <a href={% url "kitchen:dish-detail" pk=dish.id %}>{{ dish.name }}</a>
              </td>
            <td>{{ dish.price }} USD</td>
            </tr>
          {% endfor %}
        {% else %}
            <td colspan="2">== No dishes yet ==</td>
        {% endif %}

        </tbody>
      </table>
      <br>

    {% endfor %}

  {% endif %}



{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1 class="index-header">More than just food!</h1>


  <div class="card-section">

    <div class="card" style="width: 18rem;">
      <a href={% url "kitchen:cooks-list" %}>
        <img class="card-img-top" src="{% static "img/cook.jpg" %}" alt="Cook">
        <div class="card-body">
          <p class="card-text">We have {{ num_cooks }} cooks</p>
        </div>
      </a>

    </div>

    <div class="card" style="width: 18rem;">
      <a href={% url "kitchen:dishes-list" %}>
        <img class="card-img-top" src="{% static "img/dishes.jpg" %}" alt="Delicious food">
        <div class="card-body">
          <p class="card-text">...and {{ num_dishes }} delicious dishes!</p>
        </div>
      </a>
    </div>
  </div>
{% endblock %}